name: "${plugin.name}"
description: "${project.description}"

main: "${plugin.class.main}"
version: "${project.version}"
api-version: "${plugin.version.api}"

website: "${plugin.website}"
authors: ${plugin.authors}
